# Generated by Django 5.1.5 on 2025-01-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='easy_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='hard_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='medium_correct',
            field=models.IntegerField(default=0),
        ),
    ]
